roles/generate-jenkins/templates/Jenkinsfile.j2

Without env variables some container will exit on the config stage and not allow us to dump package versions for the container. 
This manually sets the entrypoint to /bin/sh to avoid that.

need to manually set the entrypoint for package dump

---

roles/generate-jenkins/tasks/main.yml
roles/generate-jenkins/templates/Jenkinsfile.j2

Discovered this when setting up new build infra for x86 nodes. 
The temp files used during builds need to be able to be deleted by a non root user.

Allow non root users on a build node to delete temp files

---

roles/generate-jenkins/templates/Jenkinsfile.j2

After pulling a tag from a deb repo realized a tilde will brok out the whole build process and not work with either dockerhub or github. 
This sanitizes the tag for everything but the argument passed to the dockerfile which is a raw string.

adding release tag sanitization for dockerhub and github endpoints

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Also removed the git directory concept after we cd into the git dir, and added a wait after the copy operation.

Adding verbose logging to package tagging process

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

@JAGFin1 the docker-documentation repo needs to have the LinuxServer-CI user added as a collaborator for this to work as that is the token being used to push. 
Also we will need to time the merge of the doc-builder build then this afterwards. This will push a readme to the endpoint once merged to master and give us a full loop test.

Add Logic to allow pushing gitbook readmes to docker-documentation

---

roles/generate-jenkins/templates/Jenkinsfile.j2

This has minimal impact , it will only re-template containers using github_devel type external release ingestion.

updating github devel endpoint for release ingestion

---

roles/generate-jenkins/templates/Jenkinsfile.j2

This will hit every single endpoint, not sure if we want to try to sneak in any other fixes on top of this. 
This will also trigger off package verions on Ubuntu variants so we will double build every one of those. 
We pulled it out originally because the awk logic kept messing up , cut is cleaner and does not have syntax problems being embedded in a docker exec like this.

Only write first two columns of ubuntu apt output

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2
root/etc/services.d/fake/run

This will sort the package_versions.txt to sparky spec. 
Also we will shellcheck off centralized logic in linuxserver/docker-shellcheck so it can be updated on the fly. 
The Xml is linked in the discord ping and comments on PRs.

#17 updating package versions adding shellcheck reporting output to discord

---

roles/generate-jenkins/templates/Jenkinsfile.j2

This has been a bug that has been a pain in my ass for some time now. 
I have been tearing apart the ci code to determine why the threads seemingly crash when taking a screenshot. 
It turns out it is a dev setting for the container that chrome requires to render complex pages properly. 
This is why the delay to render the page into an image was causing the problem to get worse as a fully rendered page is much more resource intensive to render and screenshot. 
I would normally say this should wait, but this problem leaves running containers on our x86 build nodes, we really should fix this asap.

need shm size 1gb so chrome does not crash

---

roles/generate-jenkins/templates/Jenkinsfile.j2

This is unobtrusive and optional, merging this will not waterfall any changes to the downstream repos. 
This option if defined in the jenkins-vars.yml will allow us to selectively build problem pojects on x86 as building them on arm has proven to be a pain.

adding option to use x86 to build if the project needs it

---

roles/generate-jenkins/templates/Jenkinsfile.j2

https://npm.community/t/skimdb-is-down-for-me-anyone-else/8060/8
We also need to swap out the dockerfile endpoint in thelounge and shout-irc.
https://github.com/linuxserver/docker-shout-irc/blob/master/Dockerfile#L24
https://github.com/linuxserver/docker-thelounge/blob/master/Dockerfile#L23

need to update endpoint URL as skimdb has been shut down

---

roles/generate-jenkins/templates/Jenkinsfile.j2

as noted in title, this is needed for images we may generate that are unable to be run or are not ubuntu/alpine.

add option to rip out package check logic

---

roles/generate-jenkins/templates/README.j2

Need this ability downstream in rdesktop container to define shm size. 
Will not effect any current template generation. 
Example of usage var: 
```
opt_custom_params:
- { name: "shm-size", name_compose: "shm_size", value: "1gb",desc: "We set this to 1 gig to prevent modern web browsers from crashing" }
```

need custom vars to define shm size in downstream image

---

roles/generate-jenkins/templates/FUNDING.j2

It shouldn't affect existing templates, only ones with multi sponsor links (ombi is the only one so far)

fix bug affecting multi sponsor links

---

roles/generate-jenkins/tasks/main.yml
roles/generate-jenkins/templates.yml
roles/generate-jenkins/templates/Jenkinsfile.j2
roles/generate-jenkins/templates/greetings.j2
roles/generate-jenkins/templates/stale.j2

https://github.com/actions/starter-workflows/blob/e11672e5a9026a98ce6235af089d3112ec93dbd5/automation/greetings.yml
https://github.com/actions/first-interaction
This will comment on the first issue and first PR anyone opens in any of our repos (so possibly 2 comments in every repo that a user interacts with). I set the message to encourage users to use the respective template for the repo.
https://github.com/actions/starter-workflows/blob/e11672e5a9026a98ce6235af089d3112ec93dbd5/automation/stale.yml
https://github.com/actions/stale
This will add a label to issues and pull requests that are considered stale after a period of inactivity. After another period the issue/pr will be closed. I'll bring this up in chat to discuss additional options (inactivity period, exempt labels, etc).
Per …

Use GitHub Actions Greetings and Stale

---

Jenkinsfile
roles/generate-jenkins/templates.yml
roles/generate-jenkins/templates/Jenkinsfile.j2
roles/generate-jenkins/templates/lite.j2
roles/generate-jenkins/templates/lite.j2-CUSTOM

This mounts in files from the templated stuff vs the current logic pulling it in from raw git https calls. 
When this is merged everyone needs to make sure to update their aliases to prune `README.lite` after locally templating.

template again for the readme sync and use local files to update the Readme

---

roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/README.j2

fixes the issue seen on wireguard's readme: https://github.com/linuxserver/docker-wireguard/blob/master/README.md

don't include build badge if ci tests are off

---

roles/generate-jenkins/templates/README.j2
vars/common

There are couple of `TODO:` items in the PR mainly around creating extra pages in the Gitbook hosted at docs.linuxserver.io - I don't have access to that (I couldn't find it anyway).
Anyway, the purpose of this PR is to make the README as short and succinct as possible. There are many sections here which are better suited to a central documentation project than in the README of each container. 
At this point in container adoption and maturity it's also relatively safe to assume most people are either using docker-compose or some NAS system to manage their containers - thus I look to remove the `docker create` commands as this largely is a duplicate of the more useful `compose` snippet anyway.
The general gist is "less is more".

significantly reduces readme clutter

---

.github/workflows/external_trigger.yml
.github/workflows/external_trigger_scheduler.yml
.github/workflows/package_trigger.yml
.github/workflows/package_trigger_scheduler.yml
Jenkinsfile
roles/generate-jenkins/defaults/main.yml
roles/generate-jenkins/tasks/main.yml
roles/generate-jenkins/templates.yml
roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2
roles/generate-jenkins/templates/EXTERNAL_TRIGGER_SCHEDULER.j2
roles/generate-jenkins/templates/Jenkinsfile.j2
roles/generate-jenkins/templates/PACKAGE_TRIGGER.j2
roles/generate-jenkins/templates/PACKAGE_TRIGGER_SCHEDULER.j2

Automated triggers based on jenkins-vars.yml, utilizing Github workflows
Schedulers run on cron, timers vary by repo (using hashes of repo names converted to timers), so they don't all run at the same time
Schedulers first check for live branches, existence of branch trigger workflows and github pause secrets, and then trigger the necessary workflows.

Add package and external triggers

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

Display node names in jenkins blue ocean logs to make troubleshooting easier
Example: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-jenkins-builder/detail/monthly-node/1/pipeline/121#step-132-log-1

display node name

---

roles/generate-jenkins/templates/Jenkinsfile.j2

The new version tags were missed in the clean up steps, leading to copies of all images left behind on the x86_64 builders. This should clean them up.
closes #71

clean up version tagged images

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Currently, baseimage builds skip all clean up steps, which is the desired behavior for x86 images. However, armhf and aarch64 builds are also left behind.
This PR removes the armhf and aarch64 images from x86 builders after baseimage builds

clean up arm baseimages on x86 builder

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

Especially now that we started pushing `version-` tags for images, we are having more clashes between tags of different branches.
For instance, plex and jellyfin (probably more soon) publish the stable versions at both the `latest` (focal) and the `bionic` tags. The `version-` tag is overwritten by both (whichever pushes later).
We also previously had tag clashes when either upstream apps released the same version in both their stable and dev releases, or when we use the `github_devel` trigger and push both the `dev` tag and the `latest` tag for the latest stable version.
Another undesired behavior was that it was very difficult to discern whether older releases/tags were pushed from the stable or a dev branch, since the older tags only contained the version number (ie. ombi).
This PR …

prepend with release tag if not latest

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

META_TAG and VERSION_TAG should be nearly identical. Previously, there was only one tag that was used for both image tagging and image versioning in labels. With the new prepend method, the two will be decoupled because for non-stable release tags, the image tags will be prepended with the release tag, whereas the image version labels will not.
This was missed in the previous pr and the dev and pr VERSION_TAGS were accidentally matched to the live VERSION_TAG.

fix the dev and pr build meta tags

---

Jenkinsfile
README.md
readme-vars.yml
roles/generate-jenkins/defaults/main.yml
roles/generate-jenkins/tasks/main.yml
roles/generate-jenkins/templates.yml
roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2
roles/generate-jenkins/templates/Jenkinsfile.j2
roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
vars/_container-vars-blank

- Add unraid templating support:
- New vars for `jenkins-vars.yml`: `unraid_template` (default `true`) and `unraid_template_sync` (default `true`)
- Push unraid templates to new repo: https://github.com/linuxserver/templates
- Create ignore list at the templates repo: https://github.com/linuxserver/templates/blob/main/unraid/ignore.list
- Templates will look for icons named `CONTAINERNAME-icon.png` in the docker-templates repo images, if not existing, it will use the lsio logo
- Templating will ignore any repo with `jenkins-builder` and `baseimage` in the name, as well as ones that have `unraid_template` set to `false` and ones that are listed in the `ignore.list`
- Accept `main` as alternative default branch for pushing docs and unraid templates
- Update readme local jenkins-builder …

Add unraid templating support, and minor fixes

---

roles/generate-jenkins/templates/CONTRIBUTING.j2
roles/generate-jenkins/templates/PULL_REQUEST_TEMPLATE.j2

While contributing to `docker-homeassistant` I was asked not to make an issue AND a PR for the same fix but the only reason I did both was because I read the CONTRIBUTING.md thought I should open an issue first. It was only after I made the issue, then I saw PULL_REQUEST_TEMPLATE.md which made it sound like I shouldn't have opened the issue (but still wasn't clear).
This is a small language change that would've been more clear to me.
I was confused because I read the original text as "If this is a fix for a typo in code OR a fix for …

Reduce ambiguity in what types of fixes need issues vs PR

---

package_versions.txt
roles/generate-jenkins/templates/Jenkinsfile.j2

This adds an if stanza to support dumping package versions for fedora. The logic is pretty simple just an `rpm -qa` and sort.
The additional functionality has been added to the ci  container in: 
https://github.com/linuxserver/docker-ci/commit/bdefc97df209dc26a1bc71f613208ac9b4d662c3
Should be able to merge before the July monthly is pushed.

Add fedora

---

roles/generate-jenkins/templates/DOCUMENTATION.j2

Closes https://github.com/linuxserver/docker-jenkins-builder/pull/114
Superseding the other PR by rebasing to the monthly branch.

Update Usage section for readability

---

roles/generate-jenkins/defaults/main.yml
roles/generate-jenkins/templates/Jenkinsfile.j2

Adding `armhf_native: true` to jenkins-vars.yml will set the armhf jenkins builder label to `ARMHF_NATIVE`. The current three native builders already have the new label added.
`use_qemu: true` will override this behavior and will build on x86 even if `armhf_native` is set to true.

allow building on native armhf via jenkins var

---

roles/generate-jenkins/defaults/main.yml
roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/README.j2
roles/generate-jenkins/templates/lite.j2
vars/_container-vars-blank

Webtop needs to be able to set seccomp unconfied until this https://github.com/docker/for-linux/issues/1262 is resolved so we need to present that as an optional var in the readme.

add ability to set security options in the readme

---

Jenkinsfile
roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/Jenkinsfile.j2
roles/generate-jenkins/templates/README.j2

Adding back Quay.io as they have upgraded to support manifests.
In casual use I have not noticed downtime, but that does not mean much, this build is looped with it's own logic: 
https://quay.io/repository/linuxserver.io/lsiodev-jenkins-builder/manifest/sha256:31fc9c83a08626a672b55799350f862c7d5ce920eebae6ac8b441e34bda539f0
Also using the generic text badge.

add quay back as an endpoint

---

roles/generate-jenkins/templates/Jenkinsfile.j2

semver tagging will only be done if upstream version is detected as semver
main and master branches will use naked semver tag in manifest, other branches will append branch name
date tagging is removed as it doesn't seem to provide any benefit over existing tags

add branch name to semver tag, remove date tagging

---

roles/generate-jenkins/defaults/main.yml
roles/generate-jenkins/templates/Jenkinsfile.j2

Setting jenkins var (yaml var, not env var) `build_armhf: false` in jenkins-vars.yml will generate a Jenkinsfile with all the arm32v7 build and push bits removed. The manifest will contain `x86_64` and `aarch64` only.
Default is set to `true` in jenkins builder so all existing images without the new var will have arm32v7 bits in their Jenkinsfiles (even the non multi-arch ones because the `MULTIARCH` var in jenkins-vars is an env var so it is evaluated and acted upon during actual build, not template generation).

add jenkins var `build_armhf`, default true

---

roles/generate-jenkins/defaults/main.yml
roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/README.j2
roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
vars/_container-vars-blank

@Roxedus plans to confirm the multi-line capability of the unraid template `<Requires>` tag.
This originally started with the intention of facilitating the ability to display the compse/cli information for running an external database, but it has evolved to be named generically "application" to foster inclusion of things like redis as well.

Add variables for external application snip/blocks

---

roles/generate-jenkins/defaults/main.yml
roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/README.j2
roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
vars/_container-vars-blank

- Add `opt_` prefix on sec vars that were likely copy/pasted in a previous commit.
- Removing proxy snip. it was only actually used in one image (and one deprecated image). The proxy conf comments cover the information already.

Fix inconsistent variables

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Example output for this image (jenkins-builder):
```
NAME                    VERSION                TYPE   
Jinja2                  3.0.1                  python  
MarkupSafe              2.0.1                  python  
PyNaCl                  1.4.0                  python  
PyYAML                  5.4.1                  python  
alpine-baselayout       3.2.0-r18              apk     
alpine-keys             2.4-r1                 apk     
ansible                 4.8.0                  python  
ansible                 4.8.0-r0               apk     
ansible-core            2.11.6                 python  
ansible-core            2.11.6-r1              apk     
apk-tools               2.12.7-r3              apk     
asn1crypto              1.4.0                  python  
bash …
```

Replace package_versions with syft SBOM

---

roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2

If the external trigger is alpine repo type and is multi-arch, it will check aarch64 and armv7 (if it's set to build armhf) repos to make sure they are also updated before triggering build

check other arch repos if alpine repo trigger

---

roles/generate-jenkins/templates/Jenkinsfile.j2

The S6 permission checker Github workflow checks PRs, but initial commits and other pushes to a live branch aren't checked. This PR makes the Jenkins builder check the live branch pushes and if there are missing executable bits in S6 services, it fails the build, preventing a broken image push.

check s6 service perms on live build, fail if wrong

---

roles/generate-jenkins/templates/Jenkinsfile.j2

overwrite old `arm32v7-latest` and `arm32v7-nightly`, etc. tags with fake manifest lists that result in `no matching manifest for linux/arm/v7 in the manifest list entries` when attempting to pull on armhf

push fake `arm32v7-latest` manifest

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

Removes old unused DO envs from the test stage.
`S3_BUCKET` and `S3_REGION` is set in the ci module https://github.com/linuxserver/docker-ci/blob/master/ci/ci.py#L42-L43

Remove old unused DO envs from the test stage.

---

roles/generate-jenkins/templates/Jenkinsfile.j2

- Some images are incorrectly named `containername-icon.png` in the [docker-templates](https://github.com/linuxserver/docker-templates/tree/master/linuxserver.io/img) repo. This PR will look for those if properly named image is not found

check for logo named icon as backup in unraid template

---

roles/generate-jenkins/templates/Jenkinsfile.j2

If armhf is marked as deprecated, this PR will make the Jenkinsfile check the `arm32v7-releasetag` digest for the existence of `.layers`. If not `null`, it will push a fake multi arch manifest with just the `amd64-releasetag` image.
Possibilities covered:
- If no such image digest, jq returns `null`, no push (means we never pushed an arm32v7 image anyway, so no need to overwrite with a fake manifest)
- If image digest does not contain `.layers`, jq returns `null`, no push (means we already pushed a fake multiarch manifest)
- If image digest contains `.layers`, jq returns `not "null"` and it pushed (means we were previously pushing arm32v7 images
This logic utilizes the difference between single image digests and multi image manifests.
The single image digest contains info on image layers, …

only push fake manifest if necessary

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

This is an alternative to #199 
This PR would simplify clean up greatly. Downside is, it requires all builders to be single threaded.
Now that we have proven the utility of dind containers as builders, we can rely on these containers as single threaded builders, and can run multiple instances on the same builder (ie. a 4 threaded builder would be converted to 4 separate builders, each a single threaded dind container running on the same server).
That way, we no longer have to worry about shared image layers between different builds as no builder will have more than one build running concurrently. And each builder will be a self contained and sandboxed container whose environment can be frequently wiped clean.
This allows us to do a full `docker system prune -af --volumes` at the beginning …

simplify clean up

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

This was previously causing failed builds if more than one build was happening on the same builder for the same PR at the same time. But with the next monthly it will no longer be an issue (single executor builders).

add commit sha to PR images

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Rarely used `skip_package_check` option was breaking package check builds since switch to single arch building package check builds.
This PR fixes it so that when `skip_package_check` is set to `true`, the package check builds do single or multi arch solely based on the project's setting.
PS. `skip_package_check` is used for `FROM scratch` images that only contain binaries and libraries, without the OS, such as ffmpeg's bin branch. Since there are no OS packages in those images, a triggered package check will simply build and push the image without checking installed packages or exporting the `package_versions.txt`

handle multi-arch correctly when skip_package_check is set

---

roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/README.j2

We have some syntax differences in the optional and non optional security vars. This gets them in sync and removes the need for a secondary definition of  `run_security_opt_var`

fix formatting on required security vars

---

roles/generate-jenkins/templates/Jenkinsfile.j2

This is now automatically handled by the collection feature in scarf

Remove scarf step

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Git pull before pushing, and only push the active branch to help prevent errors due to multiple builds simultaneously pushing to the same git repo.
Example issue: https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-pidgin/job/master/298/display/redirect
Git fails to push to documentation repo because another build just pushed there and the local branch is no longer up to date
```
Cloning into '/tmp/tmp.j8ZiAtFNCB/docs/docker-documentation'...
[master bb03c5a9] Bot Updating Documentation
1 file changed, 1 insertion(+)
To https://github.com/linuxserver/docker-documentation.git
! [rejected]          master -> master (fetch first)
error: failed to push some refs to 'https://github.com/linuxserver/docker-documentation.git'
hint: Updates were rejected because the remote contains …
```

prevent simultaneous git push errors

---

roles/generate-jenkins/templates/Jenkinsfile.j2

- Problem 1: Multiple builds can and do push to same repo branch in docs and unraid templates, leading to build failures due unsuccessful push (divergent branches as HEAD moved on in remote) as seen here: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-mariadb/detail/master/599/pipeline/
- Solution: Since the different builds should push changes to different files in both of those repos, there shouldn't be conflicts needing manual resolution. Therefore we can do a `git pull --rebase` right before push
- Problem 2: Above solution fails if another build happens to push in between the `pull --rebase` and `push` in the above approach (very rare case, but happens) like here: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdo …

for docs and unraid templates, use rebase option with git pull

---

roles/generate-jenkins/templates/ISSUE_TEMPLATE.bug.j2

(currently displays `linuxserver.io` instead of container name)

fix placeholder project_name

---

roles/generate-jenkins/tasks/main.yml
roles/generate-jenkins/templates.yml
roles/generate-jenkins/templates/Jenkinsfile.j2

- Run jenkins-builder as local only (1st step to removing the remote run steps that double the number of tasks, consistent behavior between local and ci, much easier to test and troubleshoot) https://github.com/linuxserver/docker-jenkins-builder/commit/6a50b4f08b8d7c9dad154f77777e6395fe1ee1fb
- Second step of removing the remote run steps would likely have to be done after all repos are updated otherwise jenkins build will fail running on an older Jenkinsfile. In such cases, a local update of templates pushed to github should fix it
- Fix deprecation (s6v2 vs s6v3 detection was working on a local run, but failing on remote. This PR hardcodes it to s6v3) https://github.com/linuxserver/docker-jenkins-builder/commit/6a50b4f08b8d7c9dad154f77777e6395fe1ee1fb
- Increase verbosity of templating …

run jenkins-builder as local only, fix deprecation, hardcode for s6v3, restructure templating

---

roles/generate-jenkins/templates/Jenkinsfile.j2

totally missed these before, but since the build-agent containers run as the default 911, it hadn't been an issue until an aws builder without build-agent ran and failed.

Set PUID/PGID when generating templates

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Jenkins seems to have a weird bug that sometimes on a new branch push, the jenkins build parameter `PACKAGE_CHECK` does not get set as an env var in bash scripts, which causes a failure in our package update check. A replay of the same build strangely is not affected by the bug and succeeds.
Here's a failed first build: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-baseimage-rdesktop/detail/fedora-40/1/pipeline/
Here's a successful replay of the same build: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-baseimage-rdesktop/detail/fedora-40/2/pipeline
In the failed build, these lines: https://github.com/linuxserver/docker-baseimage-rdesktop/blob/214af71eac5442e9e1af06628304d28c851631ca/Jenkinsfile#L497-L500 are …

modify multi detection in package check

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Properly detect exsiting templates

---

vars/common

We can't link users to a publicly visible page for a given image so it makes more sense just to have a generic link to Scarf to make users aware of what it is. At least until/if they provide the option of public stats publishing.
In any case, the URL is wrong as they've changed the site layout, so it's now in the form
`https://app.scarf.sh/packages/linuxserver-ci/docker/linuxserver%2Fplex`

Change scarf link to generic URL

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Complements https://github.com/linuxserver/docker-ci/pull/35
Add new optional ci test vars:
- `CI_SBOM_TIMEOUT` (defaults to 900s)
- `CI_WEB_SCREENSHOT_TIMEOUT` (defaults to 120s)
- `CI_WEB_SCREENSHOT_DELAY` (defaults to 10s)
- `CI_DOCKER_LOGS_TIMEOUT` (defaults to `CI_DELAY` or 120s)

add optional ci test vars

---

roles/generate-jenkins/templates/README.j2
roles/generate-jenkins/templates/README_SNIPPETS/READONLY.j2

To invoke add to readme-vars
```yaml
readonly_supported: true
readonly_message: |
Read-only operation is only possible in Server mode.
```
Adds after the end of the App Setup block with the other conditional snippets
Needs:
- https://github.com/linuxserver/docker-documentation/pull/229

Add read-only information to readme template

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Currently the node names are printed when the docker builds start, but if the build fails before then, it takes a bunch more clicks to find out which builder it ran on

print node name early

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

If docker pushes fail, retry up to 4 times with exponential backoff (powers of 5)
The delay timings will be 1s, 5s, 25s and 125s.

retry docker pushes with exponential backoff

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Makes use of `ghcr.io/linuxserver/jenkins-builder:empty` which is a copy of `docker.io/traefik@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb`
Will push an empty index for `latest`, `amd64-latest`, and `arm64v8-latest` (or relevant branch tags) when deprecating an image.

Push empty index for latest tags when deprecating image

---

filter_plugins/admonition.py
roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/DOCUMENTATION.j2-CUSTOM
roles/generate-jenkins/templates/ISSUE_TEMPLATE.bug.j2
roles/generate-jenkins/templates/ISSUE_TEMPLATE.feature.j2
roles/generate-jenkins/templates/PULL_REQUEST_TEMPLATE.j2
roles/generate-jenkins/templates/README.j2
roles/generate-jenkins/templates/README.j2-CUSTOM
roles/generate-jenkins/templates/README_SNIPPETS/DEPRECATION.j2
roles/generate-jenkins/templates/README_SNIPPETS/MEDIA.j2
roles/generate-jenkins/templates/README_SNIPPETS/UPDATING_INFO.j2
roles/generate-jenkins/templates/common_macros.j2
roles/generate-jenkins/templates/lite.j2
roles/generate-jenkins/templates/lite.j2-CUSTOM

Adapt readme to Githubs [admonition syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).
- This is already supported on dockerhub, so readme sync can still use the same file.
- Gitlab is adapting this syntax down the road. 
The new admonition filter will map MkDocs' [types](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types) to Githubs few types.

Adapt readme to Githubs alerts

---

roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2

A few images use a custom external trigger to check for upstream artifacts before triggering a new build. However, once switched over to custom, the whole external trigger is manually managed and any update to the template requires manual updates to the custom ones.
This PR adds the external artifact check into the template, activated a new block var in jenkins-vars.yml named `external_artifact_check`.
This var can be set to any multiline bash commands (written in the jinja/ansible template style) and it will be injected into the external trigger.
The only requirement is that the var sets `artifacts_found` to either `true` or `false` depending on whatever check needs to be performed.
A sample var for Emby is as follows:
```yml
external_artifact_check: |
assets=$(curl -u "${{ '{{' }} …
```

add optional artifact check via `external_artifact_check` in jenkins_vars.yml

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

Fixes Dev and PR build failures saying "Success" and also greatly simplifies the webhook code so there's only a single instance.

Fix incorrect status for dev/pr failures, simplify code

---

roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2
roles/generate-jenkins/templates/PACKAGE_TRIGGER_SCHEDULER.j2

Tested here: https://github.com/linuxserver/docker-baseimage-arch/actions/runs/11084778493/job/30800451959
- `grep -w` doesn't work with `-`
- While the front end anchor `^` works for all lines in the var, the rear end anchor `$` only works on the last line value

fix grep options and anchors

---

roles/generate-jenkins/templates/PACKAGE_TRIGGER_SCHEDULER.j2

This PR modifies the discord notification for the package trigger so that the jenkins build url is only included if there are triggered builds. If all branches are skipped, the build url will be omitted.
Tests:
1. Synclounge master added to `SKIP_PACKAGE_TRIGGER` and package trigger initiated from manually updated `triggertest` branch
- Action: https://github.com/linuxserver/docker-synclounge/actions/runs/11205332343
- Discord notification: https://discord.com/channels/354974912613449730/400217715719274506/1292599616671584336
2. Synclounge master removed from SKIP_PACKAGE_TRIGGER` and package trigger initiated from manually updated `triggertest` branch
- Action: https://github.com/linuxserver/docker-synclounge/actions/runs/11205338255
- Discord notification: …

package trigger: print build url only if there are triggered branches

---

roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/README.j2
roles/generate-jenkins/templates/README_SNIPPETS/KASM.j2

This can be setup to add information after the app setup block using the following variables: 
```
kasm_blurb: true
external_http_port: "3000"
external_https_port: "3001"
noto_fonts: "font-noto-cjk"
show_nvidia: true
```
If only the `kasm_blurb: true` is set all defaults will be set as laid out here minus the nvidia support that needs to be specifically enabled for images that support it as Alpine does not. The Alpine blurb in the Nvidia section is to cover us for webtop or other images that may be multi distro base in the future. 
The ports are needed for images that are off the default 3000 and 3001, the maintainer will need to know what font noto package to use for their image base flavor here are the current packages: 
Arch: noto-fonts-cjk
Debian/Ubuntu: fonts-noto-cjk
Alpine: …

add a kasm blurb that can be used on all KasmVNC based images

---

readme-vars.yml
roles/generate-jenkins/templates/CONTRIBUTING.j2
roles/generate-jenkins/templates/README_SNIPPETS/BUILDING_LOCALLY.j2

In our docs use the LSIO supported qemu image.

update docs to reflect using LSIO image for multi arch

---

roles/generate-jenkins/templates/Jenkinsfile.j2

This adds the CI report to the top of all releases. I think this will not only help us, but also show users transparently that the image that was released works in our testing environment. 
The only question I see here is some images do not do CI testing so the release would have a title and blank line for `CI Report`, I took this approach as those images are rare and this part of the code base is very difficult to test live so I did not want to get into refactoring.

add CI report line to the release notes

---

roles/generate-jenkins/templates/README_SNIPPETS/KASM.j2

The lossless stuff no longer needs to be docced with this change https://github.com/kasmtech/noVNC/pull/119
Also need to fix a typo in the readme for the internationalization section, the line break does not work unless it is explicitly in there. 
Want to merge to master on this on as it is a bugfix and only a readme update that effects KasmVNC based images.

fix line break in language snippet and remove lossless notice

---

Jenkinsfile
roles/generate-jenkins/templates/Jenkinsfile.j2

This enables support for SBOM and Provenance manifests to be included with builds.
Notable change to the process is to push the buildcache image at the end of the builds for *all* arches to *all* registries, and then tag them later, rather than pushing after the CI tests. This is because you can't pull and repush attestations.
Requires all build agents to be at least 537157a0-ls94
SBOM-enabled builds via https://github.com/linuxserver/docker-adguardhome-sync/tree/sbom-test
See `docker buildx imagetools inspect …

Tag buildcache

---

roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/README.j2
roles/generate-jenkins/templates/README_SNIPPETS/NONROOT.j2

Basically the same as the read_only sections. Won't be in use for a while.

Add readme/docs snippers for nonroot operation

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Skip custom readme and images containing `init_diagram: false`
Blurb being added to Jenkinsfile was tested locally for the following scenarios:
1) custom readme: not added
2) no `init_diagram`: added
3) `init_diagram: false` in readme-vars.yml: not added
~~The editing of readme-vars.yml, commit and push to github will have to be tested live after merge unfortunately.
I'm not 100% sure the double escapes `\\` in Jenkinsfile are necessary here (I believe they are, but we'll find out after merge for sure).~~
Bash script also tested by manually modifying a synclounge dev branch's Jenkinsfile to manually add an active stage for updating readme-vars.yml.
Git changes to Jenkinsfile here: https://github.com/linuxserver/docker-synclounge/compare/linuxserver:b16e431...linuxserver:48a66f2#diff-e6ffa5 …

Add init diagram to readme-vars.yml

---

roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2

One edge-case caveat to document here:
If we ever do a multi-arch build without amd64 in the future, this will need changing because it assumes there will always be an amd64 manifest to check in multi-arch builds. See line 116.
Another way to do it is to delete all annotations and then just grab the first manifest entry but that's more prone to breaking due to unforeseen changes IMO.

Fix handling of OCI indexes and manifests

---

roles/generate-jenkins/templates/DOCUMENTATION.j2
roles/generate-jenkins/templates/README.j2
roles/generate-jenkins/templates/README_SNIPPETS/KASM.j2

Move kasmvnc blurb below app specific info
Clarify kasmvnc specific hw accel info

move kasmvnc blurb, clarify hw accel section

---

roles/generate-jenkins/templates/PACKAGE_TRIGGER_SCHEDULER.j2

Consider cases where the branch may not have a Jenkinsfile because either it is deprecated or is an early dev branch
Add error resiliance when Jenkins job can't be triggered or the build description can't be modified so the scheduler doesn't fail halfway through
Tested live in a mock live branch of jackett here: https://github.com/linuxserver/docker-jackett/actions/runs/12340943736

package trigger: check for deprecated branches, handle errors better

---

roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2

Allows setting e..g. `SKIP_EXTERNAL_TRIGGER="lychee_master_v6.2.0"` to skip just that version from external trigger checks.
Will still always skip package checks because there's no external version logic in those so the var needs to be removed once the new release is available - but it means we don't have to keep checking upstream for the next version release to be able to build.

Allow skipping specific versions of upstream projects

---

roles/generate-jenkins/templates/Jenkinsfile.j2

Prune all images after selective system prune to avoid CI test image buildup
In https://github.com/linuxserver/docker-jenkins-builder/pull/321 we stopped doing an `all` system prune because it removes the buildx container, which stops us from pruning its internal image storage and lead to the disk filling up.
*But* on the x86 hosts we `load` built images into the "host" (build agent) image store for CI testing and subsequent pushes, and these weren't getting cleaned up.

Prune all images after selective system prune

---

ansible/roles/documentation/templates/README_SNIPPETS/SUPPORTED_ARCHITECTURES.j2
ansible/roles/repository/templates/Jenkinsfile.j2
ansible/vars/default.yml

This PR adds the `jenkins-vars.yml` argument `build_riscv64` (default `false`)
When set to true, it does the following:
- Builds `Dockerfile.riscv64` on native riscv64 builder and pushes to `riscv64` tag
- Adds the green checkmark for riscv64 under `Available Architectures` in the readme (if set to false, it does not add a red X, so existing readmes without riscv64 are not modified) locally tested:
Requires:
- `MULTIARCH=true` in `jenkins-vars.yml` (not able to build only amd64 and riscv64)
If `build_riscv64` is not defined or set to false, it does not modify existing readmes or Jenkinsfiles so this PR shold not have any impact on existing repo templates (locally tested)
Test results:
`baseimage-alpine:edge` dev build with locally generated Jenkinsfile: …

add support for  riscv64

---

ansible/roles/documentation/templates/README_SNIPPETS/SELKIES.j2

Need this in the snippet now that DRI3 is supported.

Selkies update

---

ansible/roles/documentation/templates/README_SNIPPETS/SELKIES.j2

New env var in the bases to set the custom websocket port so users can mix these desktop containers on the same network interface.

add custom ws port to selkies blurb
