- roles/generate-jenkins/templates/Jenkinsfile.j2
Needed for repos that have weird endpoints for versioning information.
> adding a custom bash command to the jenkinsfile if it is defined

- Jenkinsfile
- roles/generate-jenkins/templates/Jenkinsfile.j2
With more stuff churning through the system, it is very useful to have a click able link on failure if it exists.
> Pass CI URL to discord even if tests fail

- roles/generate-jenkins/templates/Jenkinsfile.j2
Ran into this with couchpotato they have a slash in their release tag for some reason
> need to remove slashes from tags also

- roles/generate-jenkins/templates/Jenkinsfile.j2
Ran into problems on first run, simplifying command and dumping all info.
> Fixes for ubuntu package dumping

- roles/generate-jenkins/templates/Jenkinsfile.j2
Will only push to gitbook if this is a master branch.
> adding gaurd to gitbook pushes to be on master branch

- Jenkinsfile
- README.md
- readme-vars.yml
- roles/generate-jenkins/templates/Jenkinsfile.j2
The release logic was loop tested on the testing branch, you can see the message in the pre-releases for this repo. This should loop test the comment feature on the PR.
> changing release notes to pull from readme-vars and comment on PR

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- roles/generate-jenkins/templates/Jenkinsfile.j2
This is a rolling Pull request so we can gradually add changes to the build logic throughout the month. 
At the end of this cycle we will create a full loop test of this current template logic on an isolated branch confirm functionality and merge this to master.
> Monthly April

- Jenkinsfile
- roles/generate-jenkins/templates/Jenkinsfile.j2
We need this for containers that exist but do not return our new version string
> fixing output of docker command to only output a string containing -ls

- Jenkinsfile
- roles/generate-jenkins/templates/Jenkinsfile.j2
If grep fails that is expected for not getting back a string containing -ls
> need to exit 0 on failures of grep match

- roles/generate-jenkins/tasks/main.yml
- roles/generate-jenkins/templates/Jenkinsfile.j2
- roles/generate-jenkins/templates/LICENSE.j2
This is a rolling Pull request so we can gradually add changes to the build logic throughout the month.
At the end of this cycle we will create a full loop test of this current template logic on an isolated branch confirm functionality and merge this to master.
> Monthly May

- Jenkinsfile
- roles/generate-jenkins/templates/Jenkinsfile.j2
> bugfix to match logic for getting the tag for comparison

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- roles/generate-jenkins/tasks/main.yml
- roles/generate-jenkins/templates/FUNDING.j2
- roles/generate-jenkins/templates/Jenkinsfile.j2
Sync with this for monthly, this might also have a series of files added for PR and Issue templates: 
https://github.com/linuxserver/docker-doc-builder/pull/31
> add open collective templating

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Jenkinsfile
- generate.yml
- roles/generate-jenkins/defaults/main.yml
- roles/generate-jenkins/tasks/main.yml
- roles/generate-jenkins/templates.yml
- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/DOCUMENTATION.j2-CUSTOM
- roles/generate-jenkins/templates/ISSUE_TEMPLATE.j2
- roles/generate-jenkins/templates/Jenkinsfile.j2
- roles/generate-jenkins/templates/PULL_REQUEST_TEMPLATE.j2
- roles/generate-jenkins/templates/README.j2
- roles/generate-jenkins/templates/README.j2-CUSTOM
- vars/_container-vars-blank
- vars/common
Making some moves here. Notable Changes: 
* all templating is now on this single container no more doc builder
* local mode no longer has different naming it just replaces the files
* Templated files are in two arrays now so in the future will just need to add them to the arrays to template additional files
Nothing is set in stone, and if we make the shift our devs need to swap up their local Aliases to just run this and remove the documentation readme before sending off commits. 
We still need finalized Issue and PR templates.
> Monthly adding loop tested logic , still waiting for finalized issue/pr templates

- roles/generate-jenkins/templates/Jenkinsfile.j2
We welcome all PR’s though this doesn’t guarantee it will be accepted.
> add step to clean up workspace

- roles/generate-jenkins/defaults/main.yml
- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/README.j2
- vars/_container-vars-blank
We welcome all PR’s though this doesn’t guarantee it will be accepted.
> Add support for hostname

- .github/FUNDING.yml
- Jenkinsfile
- roles/generate-jenkins/templates/FUNDING.j2
- roles/generate-jenkins/templates/Jenkinsfile.j2
This will amend all repos' `FUNDING.yml` to add `github: linuxserver`, which will display the Github Sponsors info in the button
> add github sponsors info to funding.yml

- roles/generate-jenkins/templates/DOCUMENTATION.j2
Currently this builds faulty documentation for compose, as seen on [airsonic](https://docs.linuxserver.io/images/docker-airsonic#docker-compose) with the optional volume, or [emby](https://docs.linuxserver.io/images/docker-emby#docker-compose) with the optional ports.
Less profanity in DMs
Built the builder, and ran trough the playbook with my modified code
> Fix duplicated statements when optional

- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/README.j2
> Remove LE reference

- roles/generate-jenkins/templates/ISSUE_TEMPLATE.j2
Attempt to offload future issues by making it clearer that docker mods might be a solution.
> Add note regarding docker mods on issue templates

- roles/generate-jenkins/templates/greetings.j2
Ref: https://github.com/linuxserver/docker-wireguard/issues/87#issuecomment-752093473
> Update greeter with new issue template links

- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/DOCUMENTATION.j2-CUSTOM
Refer to internal discussion in project channel.
These changes should not affect Gitbook, so merging should be fine.
> Add markdown title to documentation

- roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
- vars/_container-vars-blank
Escapes most instances of human-inputted text.
Add bash as the default shell, as it is in both type of baseimage.
Moves /config to advanced section.
Set defaults, as PUID, PGID and umask.
Filters away umask from readmevars input.
Introduces optional var `env_options` to create a drop-down style selector for allowed entries.
> Unraid fixes

- roles/generate-jenkins/templates/Jenkinsfile.j2
Ref: https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys
> Add labels to docker build commands

- roles/generate-jenkins/templates/CONTRIBUTING.j2
- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/DOCUMENTATION.j2-CUSTOM
- roles/generate-jenkins/templates/Jenkinsfile.j2
- roles/generate-jenkins/templates/README.j2
- roles/generate-jenkins/templates/README.j2-CUSTOM
- roles/generate-jenkins/templates/lite.j2
- roles/generate-jenkins/templates/lite.j2-CUSTOM
Update templating to generate markdown compliant with [Markdownlint](https://github.com/markdownlint/markdownlint)
Makes my editor happy on future contributions. 
Built locally, and ran on 5 random repos I had on my disk.
> Generate markdown following the rules of markdownlinter

- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/README.j2
- roles/generate-jenkins/templates/lite.j2
> Make app setup harder to miss

- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/DOCUMENTATION.j2-CUSTOM
- roles/generate-jenkins/templates/README.j2
- roles/generate-jenkins/templates/README.j2-CUSTOM
- roles/generate-jenkins/templates/lite.j2
- roles/generate-jenkins/templates/lite.j2-CUSTOM
> Change whitespace strategy

- roles/generate-jenkins/templates/Jenkinsfile.j2
Per @Roxedus's request, submitting a PR for the newline missed in 360f83eeed82d253f14e483a23abaf818ee8958a.
Missing newline triggers my OCD:
The same change was made in other places in 360f83eeed82d253f14e483a23abaf818ee8958a, so this should be pretty safe. 😛
> Add missing newline

- roles/generate-jenkins/templates/Jenkinsfile.j2
Lets us dump package versions for Arch based distros.
> adding arch package dumping support

- roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
- vars/_container-vars-blank
Should be the last PR marking automatic templates ready for public consumption
Add support for new tags, GitHub and Requires
Insert changelog
Actually mask tokens, passwords and keys
> Add support for new tags, GitHub and Requires

- roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
- vars/_container-vars-blank
Introduces some Unraid fixes and QoL changes
> Mark opt devices optional

- roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
* Should solve the root cause of linuxserver/templates#4
* Filter away deprecated branches
> Various unraid template changes

- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/README.j2
> Add portainer note

- roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
> Another round of unraid updates

- roles/generate-jenkins/templates/Jenkinsfile.j2
- roles/generate-jenkins/templates/UNRAID_TEMPLATE.j2
> Move deprecated templates to subdirectory

- roles/generate-jenkins/templates.yml
- roles/generate-jenkins/templates/ISSUE_TEMPLATE.bug.j2
- roles/generate-jenkins/templates/ISSUE_TEMPLATE.feature.j2
- roles/generate-jenkins/templates/Jenkinsfile.j2
- roles/generate-jenkins/templates/greetings.j2
This moves the issue templates to the new form based issue feature of GitHub, the result of the files can currently be seen at when opening a new issue in our [Playground](https://github.com/linuxserver/Playground/issues/new/choose).
This lays the groundwork for a more modern workflow in terms of issue handling
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
> Move to issue forms

- roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2
- roles/generate-jenkins/templates/EXTERNAL_TRIGGER_SCHEDULER.j2
- roles/generate-jenkins/templates/PACKAGE_TRIGGER.j2
- roles/generate-jenkins/templates/PACKAGE_TRIGGER_SCHEDULER.j2
- roles/generate-jenkins/templates/stale.j2
Based on changelogs, there should be no breaking changes.
> Bump actions to node16 versions

- roles/generate-jenkins/templates/.editorconfig.j2
> Add s6v3 file pattern to editorconfig

- roles/generate-jenkins/templates/greetings.j2
> Remove removed links

- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/README.j2
- roles/generate-jenkins/templates/lite.j2
- vars/common
Adds TZ as a common variable, as we have the tzdata package in the same containers we have PUID/PGID logic. 
This change makes `Etc/UTC` the timezone, and this will override the existing tz variables defined in readme-vars
> Move timezone to common_param_env_vars

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- roles/generate-jenkins/tasks/main.yml
> Rebase to 3.16, remove duplicate bash package

- roles/generate-jenkins/templates/Jenkinsfile.j2
once merged, following repo can be deprecated and archived: https://github.com/linuxserver/spaces-file-upload
> use ephemeral container to upload shellcheck to s3 via s3cmd

- entrypoint.sh
- roles/generate-jenkins/templates/PACKAGE_TRIGGER_SCHEDULER.j2
- Simplify package check scheduler cron randomization
- Update init done log message for the builder
> Simplify package scheduler

- roles/generate-jenkins/templates/Jenkinsfile.j2
> run deprecation step in shell

- .github/workflows/call_issue_pr_tracker.yml
- Jenkinsfile
- roles/generate-jenkins/templates/Jenkinsfile.j2
Add a markdown table to the PR comment stage
> Add a markdown table to the PR comment stage

- checkrun.sh
- roles/generate-jenkins/templates/Jenkinsfile.j2
> Move checkrun to jenkins repo

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- jenkins-vars.yml
- roles/generate-jenkins/tasks/main.yml
> Add logic to deprecate armhf

- roles/generate-jenkins/defaults/main.yml
handle multi-arch correctly when skip_package_check is set
> Set default arm to false

- roles/generate-jenkins/templates/Jenkinsfile.j2
https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection
> Use PUT (not POST) for protection

- roles/generate-jenkins/templates/DOCUMENTATION.j2-CUSTOM
- roles/generate-jenkins/templates/README.j2-CUSTOM
Potential fix for
https://github.com/linuxserver/docker-ffmpeg/blob/b88dba5619662ff47d4b8e0c88a9242bb0b75cdc/README.md?plain=1#L2
and 
https://github.com/linuxserver/docker-documentation/blob/3eb702a34439a2732bd9b1f743847ca53350943e/docs/images/docker-ffmpeg.md?plain=1#L5
> fix: :bug: add newlines to custom templates

- roles/generate-jenkins/templates/README_SNIPPETS/UPDATING_INFO.j2
> Remove watchtower from readme

- roles/generate-jenkins/templates/README_SNIPPETS/SUPPORTED_ARCHITECTURES.j2
> Update manifest docs link

- roles/generate-jenkins/templates/README_SNIPPETS/DOCKER_COMPOSE.j2
* Nobody understands what it is anyway
* v2/v3 schemas were merged with compose 1.27 which was released over 3 years ago (2020-09-07)
* Compose 1.x is completely EOL now anyway
> Remove schema version from sample compose

- roles/generate-jenkins/templates/Jenkinsfile.j2
> Monthly mkdocs deprecate

- roles/generate-jenkins/templates/README_SNIPPETS/HWACCEL.j2
> Switch to Nvidia toolkit

- roles/generate-jenkins/templates/common_macros.j2
> Allow " and ' in admonitions

- .github/ISSUE_TEMPLATE/issue.bug.yml
- .github/workflows/external_trigger.yml
- .github/workflows/external_trigger_scheduler.yml
- .github/workflows/package_trigger.yml
- .github/workflows/package_trigger_scheduler.yml
- Jenkinsfile
- roles/generate-jenkins/templates/Jenkinsfile.j2
Update templates for testing of pat use
> Use pat for Docker Hub

- roles/generate-jenkins/templates/Jenkinsfile.j2
> Be specific on yq

- roles/generate-jenkins/templates/Jenkinsfile.j2
Also fix readme size comparison
> create docker hub endpoint if it doesn't exist so readme sync succeeds

- roles/generate-jenkins/templates/Jenkinsfile.j2
> Redirect deprecated docs properly

- roles/generate-jenkins/templates/Jenkinsfile.j2
> Skip moving unraid template when it doesnt exist

- roles/generate-jenkins/defaults/main.yml
- roles/generate-jenkins/templates/Jenkinsfile.j2
> Control attestation via variables

- Dockerfile
- Dockerfile.aarch64
- Jenkinsfile
- jenkins-vars.yml
> Rebase to 3.20

- roles/generate-jenkins/templates/permissions.j2
> Check migration files for +x

- roles/generate-jenkins/templates/Jenkinsfile.j2
Needed with attestation manifests to ensure the arm64 image can be pulled onto an amd64 host for CI tests.
> Set platform for arm64 CI image pull

- roles/generate-jenkins/templates/Jenkinsfile.j2
> Bump shellcheck upload image to 3.20

- roles/generate-jenkins/templates/Jenkinsfile.j2
> Enable commit signing with SSH key

- .github/workflows/external_trigger.yml
- .github/workflows/external_trigger_scheduler.yml
- .github/workflows/package_trigger.yml
- .github/workflows/package_trigger_scheduler.yml
- roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2
- roles/generate-jenkins/templates/EXTERNAL_TRIGGER_SCHEDULER.j2
- roles/generate-jenkins/templates/PACKAGE_TRIGGER.j2
- roles/generate-jenkins/templates/PACKAGE_TRIGGER_SCHEDULER.j2
print node name early
Move more info to GHA's summaries.
Outputs close to this gist https://gist.github.com/Roxedus/e9ecd4be1b959293df5007bd13032f41
> Move more info to GHA's summaries

- roles/generate-jenkins/templates/Jenkinsfile.j2
> Anchor grep to prevent partial matches in unraid ignore list

- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/README_SNIPPETS/READONLY.j2
> Add Read Only to docs

- .github/workflows/external_trigger.yml
- .github/workflows/package_trigger_scheduler.yml
- Jenkinsfile
- roles/generate-jenkins/templates/Jenkinsfile.j2
Set different webhook colours for different build types (live/dev/PR)
Also adds build type to the footer and timestamp for job completion
> Set different webhook colours for different build types

- roles/generate-jenkins/templates/Jenkinsfile.j2
Gitlab appears to reject our empty index push for deprecations, so we'll just have to ignore it.
> Ignore errors on empty index push for deprecations

- roles/generate-jenkins/templates/Jenkinsfile.j2
Push empty index on deprecation for `{{ release_tag }}` and not for `${META_TAG}`
> Create empty index from *correct* tags

- roles/generate-jenkins/templates/README.j2
- roles/generate-jenkins/templates/README_SNIPPETS/USAGE.j2
> Try and help people who don't understand what optional means

- roles/generate-jenkins/templates/README.j2
Adds caps to parameters table:
> Add caps to Parameters section

- roles/generate-jenkins/templates/DOCUMENTATION.j2
> Add RO/Caps/nonroot detail to docs if defined

- roles/generate-jenkins/templates/Jenkinsfile.j2
> Fix missing $ and match order to multi-push

- roles/generate-jenkins/defaults/main.yml
- roles/generate-jenkins/templates/Jenkinsfile.j2
> Allow builder override

- roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2
> Add Accept for oci image type to ext trigger requests

- roles/generate-jenkins/defaults/main.yml
> Enable SBOM & Provenance by default

- roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2
Fixes https://github.com/linuxserver/docker-jackett/issues/156
> fix typo in external trigger

- roles/generate-jenkins/templates/DOCUMENTATION.j2
> Add D2 graph to documentation

- roles/generate-jenkins/templates/Jenkinsfile.j2
Wait for each push job individually and fail if any of them do. Currently the wait only fails if the last job fails.
> Fail build if any of the buldcache pushes fail

- roles/generate-jenkins/templates/Jenkinsfile.j2
Only difference between all the current options is the wording of the "Remote Changes" header, which means really it's just a lot of conditional code that serves no purpose.
> Simplify release notes to a common output

- roles/generate-jenkins/templates/EXTERNAL_TRIGGER.j2
Fully ports the mod code to handle all index or manifest types including SBOM/Provenance/other attestations regardless of multi-arch status.
> Fix index handling regardless of type

- readme-vars.yml
> Categorize builder

- roles/generate-jenkins/defaults/main.yml
- roles/generate-jenkins/templates/DOCUMENTATION.j2
- roles/generate-jenkins/templates/DOCUMENTATION.j2-CUSTOM
Depends on https://github.com/linuxserver/docker-documentation/pull/287
Allows https://github.com/linuxserver/docker-documentation/pull/292
> Use project_categories

- ansible/roles/github/templates/PULL_REQUEST_TEMPLATE.md.j2
- ansible/roles/github/templates/deprecation.md.j2
- ansible/roles/github/templates/issue.bug.yml.j2
- ansible/roles/github/templates/issue.feature.yml.j2
> fix deprecation logic for github files

- ansible/roles/documentation/templates/README_SNIPPETS/MEDIA.j2
- ansible/roles/documentation/templates/documentation.md.j2
- ansible/roles/documentation/templates/readme.md.j2
Reorders media blurb (and others)  to show as part of app setup, with the current header levels of the non-root and read-only blurbs. 
Clarify mount used in blurb
> Clarify media blurb

- Jenkinsfile
- ansible/roles/repository/templates/Jenkinsfile.j2
We need to try this out for builds to get going again, if we don't pin here the template updates will just revert it.
> pin to specific syft version

- ansible/roles/documentation/templates/README_SNIPPETS/SELKIES.j2
- ansible/roles/documentation/templates/documentation.md.j2
- ansible/roles/documentation/templates/readme.md.j2
Centralizing the selkies blurb for desktop images.
> add selkies blurb for readmes
